fix v9 storybook test workflow (#417)
* Fix startup command

* separate build and run commands

* Publish storybook output log

* Capture playwright test video

* Enable trace

* Move webserver managing to playwright

* Remove wait installation

* Update storybook path

* use pwsh explicitly in playwright command

* Update web server command

* Update repo path

* Update test locator

* Update timeout

* Update timeout

* Remove building storybook

* Update workflow steps

* Rename workflow file

* Minor fix

---------

Co-authored-by: Atishay Jain (from Dev Box) <atisjai@microsoft.com>

diff --git a/.github/workflows/testCoverage_v9storybook.yml b/.github/workflows/testCoverage_v9storybook.yml
--- a/.github/workflows/testCoverage_v9storybook.yml
+++ b/.github/workflows/testCoverage_v9storybook.yml
@@ -1,7 +1,7 @@
-name: "FluentUIv9Charts Test coverage"
+name: "[Charts V9] Storybook Test coverage"
 on:
-  pull_request:
-    types: [synchronize]
+  schedule:
+    - cron: "30 1 * * *"  # Runs every day at 07:00 AM IST (01:30 AM UTC)
   workflow_dispatch:
     inputs:
       repo:
@@ -62,59 +62,16 @@ jobs:
                 cd ./repo1
                 yarn
 
-            - name: Build and Run storybook
-              run: | 
-                cd ./repo1/apps/chart-docsite
-                yarn run build-storybook 
-                nohup yarn run storybook > output.log 2>&1 &  
-                npx wait-on http://localhost:3000/ --timeout 300000
-
-            - name: Run yarn pack in chart-utilities to create .tgz file
-              run: |
-                cd ./repo1/packages/charts/chart-utilities
-                yarn pack --filename chart-utilities.tgz
-              id: pack-util
-
-            - name: Run yarn pack in react-charts to create .tgz file
-              run: |
-                cd ./repo1/packages/charts/react-charts/library
-                yarn pack --filename react-charts.tgz
-              id: pack-chart-v9
-
-            - name: Upload chart-utilities.tgz as artifact
-              uses: actions/upload-artifact@v4
-              with:
-                name: chart-utilities-tgz
-                path: ./repo1/packages/charts/chart-utilities/chart-utilities.tgz
-
-            - name: Upload react-charts.tgz as artifact
-              uses: actions/upload-artifact@v4
-              with:
-                name: react-charts-tgz
-                path: ./repo1/packages/charts/react-charts/library/react-charts.tgz
-
             - name: Checkout [main] of current repo
               uses: actions/checkout@v4
               with:
                 path: contrib_repo
 
-            - name: Add chart-utils package to resolutions block
-              run: |
-                cd contrib_repo/apps/plotly_examples
-                npx json -I -f package.json -e "this.resolutions = this.resolutions || {}; this.resolutions['@fluentui/chart-utilities'] = 'file:../../../repo1/packages/charts/chart-utilities/chart-utilities.tgz';"
-
-
-            - name: Install .tgz file in Plotly examples
-              run: |
-                cd contrib_repo/apps/plotly_examples
-                yarn add ../../../repo1/packages/charts/react-charts/library/react-charts.tgz
-                yarn
-
-            - name: Run Playwright test script
+            - name: Run Playwright test script (with webServer)
               run: |
                 cd contrib_repo/apps/plotly_examples
                 npx playwright install
-                npx cross-env BASE_URL='http://localhost:3000/' npx playwright test tests/FluentUIv9ChartsSnapshotTests.spec.ts || true
+                npx playwright test tests/FluentUIv9ChartsSnapshotTests.spec.ts --config playwright-storybook-v9.config.ts || true
               continue-on-error: true
 
             - name: Zip Playwright report
@@ -123,11 +80,11 @@ jobs:
                 cd contrib_repo/apps/plotly_examples
                 Compress-Archive -Path playwright-report -DestinationPath playwright-report.zip
 
-            - name: Compute number of total tests and failures
-              uses: ./contrib_repo/.github/actions/playwright_metrics
-              with:
-                current_report: contrib_repo/apps/plotly_examples/playwright-report.json
-                baseline_report: contrib_repo/apps/plotly_examples/reports/playwright-report-v9Storybook.json        
+            # - name: Compute number of total tests and failures
+            #   uses: ./contrib_repo/.github/actions/playwright_metrics
+            #   with:
+            #     current_report: contrib_repo/apps/plotly_examples/playwright-report.json
+            #     baseline_report: contrib_repo/apps/plotly_examples/playwright-report.json        
 
             - name: Upload Playwright HTML report as artifact
               uses: actions/upload-artifact@v4
@@ -142,7 +99,7 @@ jobs:
                 path: contrib_repo/apps/plotly_examples/playwright-report.json
 
             - name: Move Playwright JSON report to reports folder for scheduled runs
-              if: github.event_name == 'schedule'
+              # if: github.event_name == 'schedule'
               shell: bash
               run: |
                 cd contrib_repo/apps/plotly_examples
@@ -150,7 +107,7 @@ jobs:
                 git add reports/playwright-report-v9Storybook.json
 
             - name: Create branch name for scheduled report
-              if: github.event_name == 'schedule'
+              # if: github.event_name == 'schedule'
               id: branch
               shell: bash
               run: |
@@ -158,7 +115,7 @@ jobs:
                 echo "branch=$BRANCH" >> $GITHUB_OUTPUT
 
             - name: Commit and push v9 scheduled report
-              if: github.event_name == 'schedule'
+              # if: github.event_name == 'schedule'
               uses: stefanzweifel/git-auto-commit-action@v5
               with:
                 branch: ${{ steps.branch.outputs.branch }}
@@ -170,7 +127,7 @@ jobs:
                 repository: contrib_repo
 
             - name: "Publish Notification for scheduled report commit"
-              if: github.event_name == 'schedule' && steps.auto-commit-action.outputs.changes_detected == 'true'
+              if: steps.auto-commit-action.outputs.changes_detected == 'true'
               shell: bash
               run: |
                 echo "v9 Playwright report committed. [Create a pull request](https://github.com/${{ github.repository }}/pull/new/${{ steps.branch.outputs.branch }})" >> $GITHUB_STEP_SUMMARY
